version: '3.8'

services:
  elasticvue:
    image: cars10/elasticvue
    container_name: elasticvue
    ports:
      - "8080:8080"
    networks:
      - php-docker
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - php-docker
    restart: unless-stopped

networks:
  php-docker:
    driver: bridge